# Generated by Django 3.2.2 on 2021-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
    ]
