# Generated by Django 3.2.2 on 2021-05-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='orders.order', verbose_name='заказ'),
        ),
    ]
